---

# Install yum packages
- name: Install common yum packages
  debug: 
    msg: 'Installing yum packages on {{ env }}'

- name: Check whether group present
  group:
    name: '{{ group }}'
    state: 'present'

- name: Check whether user present
  user:
    name: '{{ user }}'
    state: 'present'


