---

- name: Create tomcat group
  become: true
  become_method: sudo
  group:
   name: '{{ tomcat_group }}'
   state: present


- name: Create tomcat user
  become: true
  become_method: sudo
  user:
    state: present
    name: 'tomcat'
    group: 'tomcat'
    home: '{{ tomcat_user_home }}'
    createhome: no


- name: Download tomcat archive
  get_url:
    dest: '{{ tomcat_archive }}'
    url: '{{ download_url }}'


- name: Unpack tomcat archive
  command: '/bin/tar -zxf {{ tomcat_archive }} -C {{ download_folder }}'
  args:
    creates: '{{ catalina_base }}'


- name: Symlink tomcat installation directory
  file: 
    src: '{{ catalina_base }}'
    path: '{{ tomcat_user_home }}'
    state: link


- name: Change ownership of tomcat installation directory
  file: 
    path: '{{ tomcat_user_home }}/'
    owner: '{{ tomcat_user }}'
    group: '{{ tomcat_group }}'
    state: directory
    recurse: yes


- name: Set up CATALINA PATHs
  template: 
    src: 'tomcat.sh.j2'
    dest: '/etc/profile.d/tomcat.sh'
    owner: '{{ vagrant_user }}'
    group: '{{ vagrant_group }}'
    mode: 0644


- name: Copy server.xml template config file
  template:
    src: 'conf/server.xml.j2'
    dest: '{{ tomcat_user_home }}/conf/server.xml'
    backup: yes


- name: Copy tomcat-users.xml config file
  template:
    src: 'conf/tomcat-users.xml.j2'
    dest: '{{ tomcat_user_home }}/conf/tomcat-users.xml'
    backup: yes


- name: Create tomcat init script in '/etc/init.d/tomcat'
  template: 
    src: 'init/tomcat-init.sh.j2'
    dest: '/etc/init.d/tomcat'
    owner: 'root'
    group: 'root'
    mode: 0766


- name: Start tomcat service
  shell: '/etc/init.d/tomcat start'


- name: Wait for tomcat to start
  wait_for:
    port: '{{ http_port }}'
    timeout: 60




