---

- name: Download java tar gz
  get_url:
    headers: 'Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    dest: '{{ java_archive }}'
    url: '{{ download_url }}'
    validate_certs: true


- name: Unpack archive
  command: '/bin/tar -zxf {{ java_archive }} -C {{ download_folder }}'
  args:
    creates: '{{ java_home }}'


- name: Set ownership
  file:
    state: directory
    path: '{{ java_home }}'
    owner: '{{ vagrant_user }}'
    group: '{{ vagrant_group }}'
    recurse: yes

- name: Set up JAVA_HOME and JRE_HOME
  template: 
    src: 'java.sh.j2'
    dest: '/etc/profile.d/java.sh'
    owner: '{{ vagrant_user }}'
    group: '{{ vagrant_group }}'
    mode: 0644


- name: Make Java available for system
  command: 'alternatives --install "/usr/bin/java" "java" "{{ java_home }}/bin/java" 1'


# - name: Remove tar.gz java archive
# file:
#   state: 'absent'
#   path: '{{ java_archive }}'