---

# This playbook is for webservers group

- hosts: webservers
  remote_user: '{{ user }}'
  become: yes
  become_method: 'sudo'
  roles:
    - common
    # - selinux
    # - java
    # - tomcat
    # - postgres